services:

  backend:
    build:
      context: ./
      dockerfile: ./backend/AudioProcessing.API/Dockerfile
    container_name: audio_backend
    restart: always
    depends_on:
      postgres:
        condition: service_started
      minio:
        condition: service_started
      kafka-1:
        condition: service_healthy
      kafka-setup:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=audio_db;Username=audio;Password=audio123
      Kafka__BootstrapServers: kafka-1:9092,kafka-2:9093,kafka-3:9094
      Minio__Endpoint: minio:9000
      Minio__AccessKey: minio
      Minio__SecretKey: minio123
      Minio__Bucket: audio-files
      Minio__Secure: "false"
    ports:
      - "5000:8080"  
    networks:
      - audio_net


  worker:
    build:
      context: ./
      dockerfile: ./workers/AudioProcessing.Worker/Dockerfile
    container_name: audio_worker
    restart: always
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-setup:
        condition: service_completed_successfully
      backend:
        condition: service_started
    environment:
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=audio_db;Username=audio;Password=audio123
      Kafka__BootstrapServers: kafka-1:9092,kafka-2:9093,kafka-3:9094
      Minio__Endpoint: minio:9000
      Minio__AccessKey: minio
      Minio__SecretKey: minio123
      Minio__Bucket: audio-files
      Minio__Secure: "false"
    networks:
      - audio_net

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: audio_ml_service
    restart: always
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-setup:
        condition: service_completed_successfully
      minio:
        condition: service_started
    networks:
      - audio_net
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: audio_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - audio_net

  postgres:
    image: postgres:15
    container_name: audio_postgres
    restart: always
    environment:
      POSTGRES_USER: audio
      POSTGRES_PASSWORD: audio123
      POSTGRES_DB: audio_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - audio_net

  minio:
    image: minio/minio:latest
    container_name: audio_minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_DOMAIN: localhost
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   
      - "9001:9001"   
    volumes:
      - minio_data:/data
    networks:
      - audio_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: audio_zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - audio_net

  kafka-1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - audio_net

  kafka-2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9093"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - audio_net

  kafka-3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-3
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9094"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - audio_net

  kafka-setup:
    image: confluentinc/cp-kafka:7.5.0
    container_name: audio_kafka_setup
    restart: "no"
    networks:
      - audio_net
    depends_on:
      kafka-1:
        condition: service_healthy 
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      echo 'Ожидание готовности Kafka...'
      sleep 10
      echo 'Создание топиков...'
      
      kafka-topics --bootstrap-server kafka-1:9092 --create --if-not-exists --topic job.created --partitions 3 --replication-factor 3
      
      kafka-topics --bootstrap-server kafka-1:9092 --create --if-not-exists --topic job.prepared --partitions 3 --replication-factor 3
      
      kafka-topics --bootstrap-server kafka-1:9092 --create --if-not-exists --topic job.completed --partitions 3 --replication-factor 3
      
      kafka-topics --bootstrap-server kafka-1:9092 --create --if-not-exists --topic job.failed --partitions 3 --replication-factor 3
      
      echo 'Топики созданы:'
      kafka-topics --list --bootstrap-server kafka-1:9092
      "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: audio_kafka_ui
    restart: always
    depends_on:
      - kafka-1
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9093,kafka-3:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - audio_net
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: audio_pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - audio_net
    volumes:
      - pgadmin_data:/var/lib/pgadmin


networks:
  audio_net:
    driver: bridge

volumes:
  pg_data:
  minio_data:
  redis_data:
  pgadmin_data:
